name: terratest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terratest:
    uses: trussworks/shared-actions/.github/workflows/terratest.yml@create-terratest-workflow
    secrets: inherit
