name: terratest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terratest:
    uses: trussworks/shared-actions/.github/workflows/terratest.yml@afbe1537997f0d39085407ed902884875e595a2b
