name: terratest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terratest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install pre-commit
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install terraform-docs
          pip install pre-commit
      - name: Restore Pre-Commit Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-dot-cache-{{ hashFiles(.pre-commit-config.yaml') }}
      - name: Restore Go Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-mod-sources-v1-{{ hashFiles('go.sum') }}
      - name: Run terratest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          temp_role=$(aws sts assume-role --role-arn arn:aws:iam::313564602749:role/circleci --role-session-name circleci)
          export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
          export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
          export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
          make test
